### PR TITLE
fix: relays annotation value is readonly and cannot be updated

### PR DESCRIPTION
**Pull request by niravparikh05**
### What does this PR change?

- Borne out of #140 

### Does the PR depend on any other PRs or Issues? If yes, please list them.

- No

### Checklist

I confirm, that I have...

- [ ] Read and followed the contributing guide in `CONTRIBUTING.md`
- [ ] Added tests for this PR
- [ ] Formatted the code using `go fmt` (if applicable)
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [ ] Updated `CHANGELOG.md`

### CODE REVIEW

**Review by akshay196 — CHANGES_REQUESTED** [review]
@niravparikh05  Please check my comment on the issue: https://github.com/paralus/paralus/issues/140#issuecomment-1591530406

**Comment by niravparikh05** [comment]
@akshay196 thanks for the review comments, after our discussion have made necessary changes.

**Review by akshay196 — APPROVED** [review]

**Comment by akshay196** [comment]
Unlinked https://github.com/paralus/paralus/issues/140 issue from this PR.

**Comment by akshay196** [comment]
Need to update db entries for older clusters to move to new logic in this PR

After upgrading from 0.2.0 to 0.2.5, we had to go into the database for each clusters annotations and change “relay” to “paralus.dev/relay” or else the bootstrap file would have an empty relay value for the relay-agent-config configmap

**Pull request merged**
