### PR TITLE
Fix: validate non empty projects for delete

### PR DESCRIPTION
**Pull request by mabhi**
Signed-off-by: mabhi <abhijit.mukherjee@infracloud.io>

### What does this PR change?

- Resolves issue [141](https://github.com/paralus/paralus/issues/141)
- Validate delete project requests for presence of clusters inside the target project

### Does the PR depend on any other PRs or Issues? If yes, please list them.

- No

### Checklist

I confirm, that I have...

- [x] Read and followed the contributing guide in `CONTRIBUTING.md`
- [x] Added tests for this PR
- [ ] Formatted the code using `go fmt` (if applicable)
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [x] Updated `CHANGELOG.md`

### CODE REVIEW

**Review by niravparikh05 — APPROVED** [review]
this looks good, in addition to these changes can you take care of below,

In get, update, delete cluster, we do not consider project passed in request while cluster select query and it solely relies on just the cluster id / name which may cause unwarranted issues. Please add project id check to the query as well

**Comment by mabhi** [comment]
Made changes in `Get` and `Update`. `Delete` calls `Get` hence validation taken care of implicitly.

**Review by niravparikh05 — CHANGES_REQUESTED** [review]
there seems to be issues while cluster bootstrapping with these changes

"caller":"agent/agent.go:351","msg":"Relay Agent::config: &{TemplateToken:cfnk1nmg8tqq1ldnkng0 TemplateName: Scheme: Mode: Addr:console.paralus.local:80 ClientID:cfnlnd6g8tqhmt0fl9kg ClientIP:10.244.0.5 Name:relay-agent-8fbcb9868-f8sqz PrivateKey:[] CSR:[] Certificate:[] CACertificate:[] ServerHost: ServerPort:0} "}
[POST /v2/sentry/bootstrap/{templateToken}/register][500] bootstrapRegisterBootstrapAgentInternalServerError  map[code:2 message:sql: no rows in result set]

There are multiple agent register request from target cluster however paralus controller is unable to register

**Comment by mabhi** [comment]
@niravparikh05 fixed changes. added project id during cluster bootstraping. As this has become mandatory.

**Review by niravparikh05 — APPROVED** [review]
lgtm

**Pull request merged**
