### PR TITLE
chore: Remove misleading helm labels

### PR DESCRIPTION
**Pull request by Joibel**
The downloaded yaml for relay clients contains misleading labelling and annotations, remove them

### What does this PR change?

The downloaded yaml for relay clients contains misleading labelling and annotations, remove them

### Does the PR depend on any other PRs or Issues? If yes, please list them.

No

### Checklist

I confirm, that I have...

- [x] Read and followed the contributing guide in `CONTRIBUTING.md`
- [ ] Added tests for this PR
- [ ] Formatted the code using `go fmt` (if applicable)
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [x] Updated `CHANGELOG.md`

### CODE REVIEW

**Review by niravparikh05 — COMMENTED** [review]
thanks @Joibel for your contribution ! looks good to me. just one thought, we can retain the label and change the managed by value from helm to paralus as these are created while bootstrapping an imported cluster. It may be easier to obtain all the objects created by paralus if a need arises.

labels:
    app.kubernetes.io/managed-by: Paralus

**Comment by Joibel** [comment]
None of the other objects in the bootstrapping bundle have labels, so I was aiming originally for consistency.

I'd say a managed-by label here would also be misleading as the objects are just provided, as is, and never automatically updated by the host paralus system as far as I can tell. They are just objects to me managed by the sysadmin right now aren't they?

**Comment by niravparikh05** [comment]
> None of the other objects in the bootstrapping bundle have labels

Good point, as part of this pr can we add labels to all objects that currently do not have ?

Also, we have a feature item in roadmap where we would like to upgrade relay-agents from console or during upgrade.

I am still inclined towards using managed-by considering this feature in mind as technically paralus will be managing these in future.

**Comment by Joibel** [comment]
Ok, I've done that.

**Comment by niravparikh05** [comment]
thanks @Joibel, changes look good. Can you run go generate from internal/cluster package which will update the content in fixtures.go, this is required so reflect the changes while generating the bootstrap yaml and commit those too so that we can have this merged.

**Comment by Joibel** [comment]
@niravparikh05  :+1:, that is done

**Review by niravparikh05 — APPROVED** [review]
thanks for your first contribution @Joibel, pr is good to go.

**Pull request merged**
