### PR TITLE
CI: added golangci-lint to the go.yml workflow

### PR DESCRIPTION
**Pull request by jaydee029**
### What does this PR change?

- Adds golang-ci lint action to go.yml workflow
- added .golangci.yml file to the root of the project

### Does the PR depend on any other PRs or Issues? If yes, please list them.

- #184

### Checklist

I confirm, that I have...

- [x] Read and followed the contributing guide in `CONTRIBUTING.md`
- [x] Added tests for this PR(not applicable)
- [x] Formatted the code using `go fmt` (if applicable)
- [x] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [ ] Updated `CHANGELOG.md`

### CODE REVIEW

**Comment by jaydee029** [comment]
@akshay196 please review and suggest changes (if any), i'll  raise another pr for fixing linting errors.

**Comment by jaydee029** [comment]
Hey @akshay196 @niravparikh05 are we proceeding with this? I have various other changes ready but its better to get this merged first.

**Comment by jaydee029** [comment]
@akshay196 i have fixed the timeout error , on the ci github action, it should work fine now.

**Comment by jaydee029** [comment]
@akshay196  Does this require any further improvements?

**Review by akshay196 — APPROVED** [review]

**Comment by jaydee029** [comment]
@akshay196 if we enable the linters , it will at least prevent any new linting errors, by the time the older ones are fixed.

**Comment by akshay196** [comment]
@jaydee029  The `main` branch CI will start failing because workflow start scanning `main` branch as per its trigger rule. I think `only-new-issues` flag only work for PR but for branch it scans everything.

Anyways we can start with fixing issues in main branch and eventually PRs also gets scan as we enable linters.

**Comment by jaydee029** [comment]
I think the CI scans only the contents of the PR that is raised, in my case it didn't fail on the last commit I made

**Pull request merged**
